name: C/C++ CI

on:
  push:
    branches: [master, develop, testing, libusb_project]
  pull_request:
    branches: [master, develop, testing, libusb_project]

jobs:
  # Linux

  job_linux_20_04_64_gcc:
    name: ubuntu-20.04 gcc
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: sudo apt update && sudo apt-get install gcc-10 libusb-1.0.0-dev libgtk-3-dev rpm
      - name: make debug
        run: sudo make clean && make debug
      - name: make test
        run: sudo make clean && make test
      - name: make release
        run: sudo make clean && make release
      - name: sudo make install
        run: sudo make clean && sudo make install
      - name: sudo make package
        run: sudo make package
      - name: sudo make uninstall
        run: sudo make uninstall && sudo make clean

  job_linux_20_04_32_gcc:
    name: ubuntu-20.04 gcc 32-bit
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: sudo apt update && sudo apt-get install gcc-10 libusb-1.0.0-dev libgtk-3-dev rpm
      - name: Set compiler flags
        run: |
          CFLAGS="$CFLAGS -m32"
          CXXFLAGS="$CXXFLAGS -m32"
          LDFLAGS="$LDFLAGS -m32"
      - name: make debug
        run: sudo make clean && make debug
      - name: make test
        run: sudo make clean && make test
      - name: make release
        run: sudo make clean && make release
      - name: sudo make install
        run: sudo make clean && sudo make install
      - name: sudo make package
        run: sudo make package
      - name: sudo make uninstall
        run: sudo make uninstall && sudo make clean

  job_linux_20_04_64_clang:
    name: ubuntu-20.04 clang
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: sudo apt update && sudo apt-get install clang-12 libusb-1.0.0-dev libgtk-3-dev rpm
      - name: make debug
        run: sudo make clean && make debug
      - name: make test
        run: sudo make clean && make test
      - name: make release
        run: sudo make clean && make release
      - name: sudo make install
        run: sudo make clean && sudo make install
      - name: sudo make package
        run: sudo make package
      - name: sudo make uninstall
        run: sudo make uninstall && sudo make clean

  job_linux_20_04_32_clang:
    name: ubuntu-20.04 clang 32-bit
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: sudo apt update && sudo apt-get install clang-12 libusb-1.0.0-dev libgtk-3-dev rpm
      - name: Set compiler flags
        run: |
          CFLAGS="$CFLAGS -m32"
          CXXFLAGS="$CXXFLAGS -m32"
          LDFLAGS="$LDFLAGS -m32"
      - name: make debug
        run: sudo make clean && make debug
      - name: make test
        run: sudo make clean && make test
      - name: make release
        run: sudo make clean && make release
      - name: sudo make install
        run: sudo make clean && sudo make install
      - name: sudo make package
        run: sudo make package
      - name: sudo make uninstall
        run: sudo make uninstall && sudo make clean

  job_linux_22_04_64_gcc:
    name: ubuntu-22.04 gcc
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: sudo apt update && sudo apt-get install gcc-12 libusb-1.0.0-dev libgtk-4-dev rpm
      - name: make debug
        run: sudo make clean && make debug
      - name: make test
        run: sudo make clean && make test
      - name: make release
        run: sudo make clean && make release
      - name: sudo make install
        run: sudo make clean && sudo make install
      - name: sudo make package
        run: sudo make package
      - name: sudo make uninstall
        run: sudo make uninstall && sudo make clean

  job_linux_22_04_32_gcc:
    name: ubuntu-22.04 gcc 32-bit
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: sudo apt update && sudo apt-get install gcc-12 libusb-1.0.0-dev libgtk-4-dev rpm
      - name: Set compiler flags
        run: |
          CFLAGS="$CFLAGS -m32"
          CXXFLAGS="$CXXFLAGS -m32"
          LDFLAGS="$LDFLAGS -m32"
      - name: make debug
        run: sudo make clean && make debug
      - name: make test
        run: sudo make clean && make test
      - name: make release
        run: sudo make clean && make release
      - name: sudo make install
        run: sudo make clean && sudo make install
      - name: sudo make package
        run: sudo make package
      - name: sudo make uninstall
        run: sudo make uninstall && sudo make clean

  job_linux_22_04_64_clang:
    name: ubuntu-22.04 clang
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: sudo apt update && sudo apt-get install clang-14 libusb-1.0.0-dev libgtk-4-dev rpm
      - name: make debug
        run: sudo make clean && make debug
      - name: make test
        run: sudo make clean && make test
      - name: make release
        run: sudo make clean && make release
      - name: sudo make install
        run: sudo make clean && sudo make install
      - name: sudo make package
        run: sudo make package
      - name: sudo make uninstall
        run: sudo make uninstall && sudo make clean

  job_linux_22_04_32_clang:
    name: ubuntu-22.04 clang 32-bit
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: sudo apt update && sudo apt-get install clang-14 libusb-1.0.0-dev libgtk-4-dev rpm
      - name: Set compiler flags
        run: |
          CFLAGS="$CFLAGS -m32"
          CXXFLAGS="$CXXFLAGS -m32"
          LDFLAGS="$LDFLAGS -m32"
      - name: make debug
        run: sudo make clean && make debug
      - name: make test
        run: sudo make clean && make test
      - name: make release
        run: sudo make clean && make release
      - name: sudo make install
        run: sudo make clean && sudo make install
      - name: sudo make package
        run: sudo make package
      - name: sudo make uninstall
        run: sudo make uninstall && sudo make clean
  
  job_win_latest_msvc:
    name: Windows (Latest) MSVC
    runs-on: windows-latest
    steps:
      - uses: ilammy/msvc-dev-cmd@v1.4.1
      - name: "checkout"
        uses: actions/checkout@v2
      - name: compile
        uses: threeal/cmake-action@v2.0.0
